[build]
  publish = "."

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, no-cache, must-revalidate"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, no-cache, must-revalidate"
